# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diario_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDeInteresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descri\xe7\xe3o')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Diario', verbose_name='Di\xe1rio')),
            ],
        ),
    ]
