# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_localdeinteresse_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='descricao',
            field=models.PositiveIntegerField(choices=[(1, 'Amigo'), (2, 'Conhecido'), (3, 'N\xe3o conhe\xe7o'), (4, 'Inimigo')], verbose_name='Descri\xe7\xe3o'),
        ),
    ]
