# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'verbose_name_plural': 'Notifica\xe7\xf5es'},
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='seguidores',
            field=models.BooleanField(default=True),
        ),
    ]
