# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('api', '0006_auto_20181027_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacao',
            name='grupo',
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='grupo',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
    ]
