# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181030_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacao',
            name='grupo',
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='grupos',
            field=models.ManyToManyField(to='api.Grupo'),
        ),
    ]
