# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181030_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='diarios',
            field=models.ManyToManyField(to='api.Diario'),
        ),
    ]
