# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recomendacao_diarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cidade_atual',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade_natal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
