# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181108_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='diarios',
            field=models.ManyToManyField(blank=True, to='api.Diario'),
        ),
    ]
